version: "2.4"
services:
  utask:
    build: .
    container_name: dsrhub_utask
    restart: on-failure
    command: ["/wait-for-it.sh", "db:5432", "--", "/app/utask"]
    environment:
      DEBUG:              'true'
      DEV:                'true'
      CONFIGURATION_FROM: 'env:CFG'
      CFG_DATABASE:       'postgres://user:pass@db/utask?sslmode=disable'
      CFG_UTASK_CFG:      '{"admin_usernames":["admin"],"application_name":"ÂµTask"}'
      CFG_BASIC_AUTH:     '{"admin":"1234","resolver":"3456","regular":"5678"}'
      CFG_ENCRYPTION_KEY: '{"identifier":"storage","cipher":"aes-gcm","timestamp":1535627466,"key":"e5f45aef9f072e91f735547be63f3434e6de49695b178e3868b23b0e32269800"}'
    ports:
      - "8081:8081"
    volumes:
      - "./templates:/app/templates"
    depends_on:
      - db
      - migrate

  migrate:
    build: .
    container_name: dsrhub_migrate
    command: ["/wait-for-it.sh", "db:5432", "--", "sql-migrate", "up", "-env", "postgres"]
    environment:
      CFG_DATABASE: 'postgres://user:pass@db/utask?sslmode=disable'
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:9.5.3
    container_name: dsrhub_db
    restart: on-failure
    environment:
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB:       utask

  openmock:
    image: dsrhub/mock
    container_name: dsrhub_openmock
    restart: on-failure
    volumes:
      - "./mocks/openmock_templates:/data/templates"
    ports:
      - "9999:9999"
      - "50051:50051"

  functional_test:
    image: zhouzhuojie/docker-venom
    container_name: dsrhub_functional_test
    entrypoint: ''
    command: sh -c "tail -F /dev/null"
